language: c

compiler:
  - clang
  - gcc

before_script: 
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq bc clang ccache clang-format-6.0 clang-tidy cmake git lcov python3 python3-yaml doxygen graphviz
  - sudo apt-get install -y -qq shellcheck 
  - sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-6.0 10
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  - export NUMCPUS=`grep -c '^processor' /proc/cpuinfo`
  - echo NUMCPUS=$NUMCPUS
  - export LSAN_OPTIONS=fast_unwind_on_malloc=0
  - ccache -s

script: 
  - mkdir build
  - cd build
  - ../scripts/test-all.sh
  - bash ./shell-lint.sh
  - npm install -g markdownlint -cli
  - markdownlint --ignore ./build/ --ignore ./lib/
  - make test

notifications:
  email: false